### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by HTDerekLiu** [jiangzhongshi/bijective-projection-shell#5]
Thanks for sharing the implementation :) When I try to compile this on my Mac, I got this error. Could you give me some guidance on how to fix it? 
```
/bijective-projection-shell/src/prism/predicates/triangle_triangle_intersection.cpp:617:11: error: 
      no viable conversion from 'tuple<Eigen::Matrix<double, 1, 2, 1, 1, 2>
      &&, Eigen::Matrix<double, 1, 2, 1, 1, 2> &&>' to 'const tuple<Vec2d
      &, Vec2d &>'
          std::forward_as_tuple(to2d(p, t), to2d(q, t)),
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/tuple:616:5: note: 
      candidate constructor not viable: no known conversion from
      'tuple<Eigen::Matrix<double, 1, 2, 1, 1, 2> &&, Eigen::Matrix<double, 1,
      2, 1, 1, 2> &&>' to 'const std::__1::tuple<Eigen::Matrix<double, 1, 2, 1,
      1, 2> &, Eigen::Matrix<double, 1, 2, 1, 1, 2> &> &' for 1st argument
    tuple(tuple const&) = default;
```

Best,

**Comment by jiangzhongshi** [comment]
My guess is that this is an old version of the compiler, without proper c++17 support

If it is helpful, here is the travis record https://github.com/jiangzhongshi/bijective-projection-shell/actions/runs/381457499

**Comment by jiangzhongshi** [comment]
If you are looking for a workaround, maybe try replace `forward_as_tuple` with `tuple`

**Comment by HTDerekLiu** [comment]
Wooo thanks a lot!! After updating to Clang 12 (I was using Clang 11), it compiled :) Thanks for saving my day.
