### ISSUE TITLE
Test data?

### ISSUE THREAD

**Issue by alecjacobson** [jiangzhongshi/bijective-projection-shell#6]
I've got the library and executable compiled. I'd like to try some of the examples mentioned in the FigureScripts.md but can't find the data. For example, where can I find `leg-intersect.obj` to reproduce Figure 23?

**Comment by jiangzhongshi** [comment]
Hi Alec,

Thanks for the interest in our project!
I apologize for the data situation, FigureScript was written during the submission in the additional materials, and I have yet to make the data public.

I will try to make this repo more accessible next month.

As for the specific leg model, it can be found here. https://github.com/jiangzhongshi/Scaffold-Map/blob/master/leg-intersect.off
Then this example should be run as
`./breve_bin -i leg-intersect.off shell --simplify-shell --allow-intersect `
(and possibly circumvent the precondition)

**Comment by jiangzhongshi** [comment]
If you need the raw data, I can pack them (except ones from Thingi10k :) ) to google drive.

**Comment by alecjacobson** [comment]
thanks!
