### ISSUE TITLE
How to get output mesh in same coordinate system as input?

### ISSUE THREAD

**Issue by alecjacobson** [jiangzhongshi/bijective-projection-shell#7]
Me again, sorry to be a pain.

I didn't know how to extract the output mesh from the .h5 output (do you have handy tools for this?), so in the meantime I added 

        igl::write_triangle_mesh("shell.ply",mB,F);

at around line 286 of `src/construct_shell.cpp`. This outputs the shell, but it seems to be normalized to the unit cube. Is that correct understanding? Is the normalization as simple as:

```
V = (V-min(V))/max(max(V)-min(V));
```
?

**Comment by jiangzhongshi** [comment]
Hi Alec,

I usually use the python package `h5py` to read the output and I am generally happy with the tool and format, where the fields
`mbase`, `mV`, `mtop` along with `mF` represents the shell. What you have should be
fine too, but only the bottom surface.

You are correct that I perform normalization during the read mesh, to simplify
edge length setting inside. And I believe your formula is what I do.
More specifically,
 
```
inline void put_in_unit_box(RowMatd& V) {
  if (V.rows() == 0) return;
  V.rowwise() -= V.colwise().minCoeff();
  V /= V.maxCoeff();
}
```

**Comment by alecjacobson** [comment]
Thanks!

**Comment by XuRongYan** [comment]
Hi, I'm sorry, I still didn't know how to get output mesh from the .h5 file.
I tried the h5py to parse the .h5 file, but I didn't know if there is any python library that can help me to get the output mesh?

**Comment by jiangzhongshi** [comment]
Hi XuRongYan,

The output of our algorithm is a shell structure, with three layers of coordinates (`mbase`, `mF`), (`mV`, `mF`), (`mtop`, `mF`), 
and they represent meshes.

Suppose you want to get an obj or ply output, I recommend using `igl` through `conda install -c conda-forge igl` with the following syntax.
```
igl.write_triangle_mesh('example.ply', V, F)
```

**Comment by XuRongYan** [comment]
Thanks.
It worked.
And the code is just like this:
````
import h5py
import igl

f = h5py.File('leg-intersect.off.h5', 'r')

mF = f['mF']
mV = f['mV']
mBase = f['mbase']
mTop = f['mtop']

igl.write_triangle_mesh('base.ply', mBase[()], mF[()])
igl.write_triangle_mesh('middle.ply', mV[()], mF[()])
igl.write_triangle_mesh('top.ply', mTop[()], mF[()])
````
